; -----------------------------------------------------------------------------
; Tables

PUSHS
SECTION "tbengine_data", ROM0, ALIGN[8]

; align these tables to pages so indexing is easier/faster

; page 0

; Vibrato tables
; A vibrato table contains 16 samples of quadrant II for a sine wave
; There are 16 tables each with a different extent (amplitude)
tbe_dVibratoTable::
    ; this table was generated by genvibrato.py
    ; $ genvibrato.py asm
    DB $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00 ; extent =   1
    DB $02, $02, $02, $02, $02, $02, $02, $02, $01, $01, $01, $01, $01, $01, $00, $00 ; extent =   2
    DB $03, $03, $03, $03, $03, $03, $02, $02, $02, $02, $02, $01, $01, $01, $01, $00 ; extent =   3
    DB $04, $04, $04, $04, $04, $04, $03, $03, $03, $03, $02, $02, $02, $01, $01, $00 ; extent =   4
    DB $05, $05, $05, $05, $05, $04, $04, $04, $04, $03, $03, $02, $02, $01, $01, $00 ; extent =   5
    DB $07, $07, $07, $07, $06, $06, $06, $05, $05, $04, $04, $03, $03, $02, $01, $01 ; extent =   7
    DB $0A, $0A, $0A, $0A, $09, $09, $08, $08, $07, $06, $06, $05, $04, $03, $02, $01 ; extent =  10
    DB $0C, $0C, $0C, $0B, $0B, $0B, $0A, $09, $08, $08, $07, $06, $05, $03, $02, $01 ; extent =  12
    DB $0E, $0E, $0E, $0D, $0D, $0C, $0C, $0B, $0A, $09, $08, $07, $05, $04, $03, $01 ; extent =  14
    DB $11, $11, $11, $10, $10, $0F, $0E, $0D, $0C, $0B, $09, $08, $07, $05, $03, $02 ; extent =  17
    DB $16, $16, $16, $15, $14, $13, $12, $11, $10, $0E, $0C, $0A, $08, $06, $04, $02 ; extent =  22
    DB $1E, $1E, $1D, $1D, $1C, $1A, $19, $17, $15, $13, $11, $0E, $0B, $09, $06, $03 ; extent =  30
    DB $2C, $2C, $2B, $2A, $29, $27, $25, $22, $1F, $1C, $18, $15, $11, $0D, $09, $04 ; extent =  44
    DB $40, $40, $3F, $3D, $3B, $38, $35, $31, $2D, $29, $24, $1E, $18, $13, $0C, $06 ; extent =  64
    DB $60, $60, $5E, $5C, $59, $55, $50, $4A, $44, $3D, $35, $2D, $25, $1C, $13, $09 ; extent =  96
    DB $7F, $7E, $7D, $7A, $75, $70, $6A, $62, $5A, $51, $47, $3C, $31, $25, $19, $0C ; extent = 127

; page 1

;
; Command function pointer table
;
tbe_dCommandTable:
    ; effect commands
    DW _tbe_cmdFnCall
    DW _tbe_cmdFnRet
    DW _tbe_cmdFnHalt
    DW _tbe_cmdFnTempo
    DW _tbe_cmdFnSfx
    DW _tbe_cmdFnSfxStop
    DW _tbe_cmdFnArp
    DW _tbe_cmdFnPitchSlideUp
    DW _tbe_cmdFnPitchSlideDown
    DW _tbe_cmdFnNoteSlideUp
    DW _tbe_cmdFnNoteSlideDown
    DW _tbe_cmdFnTune
    DW _tbe_cmdFnPortamento
    DW _tbe_cmdFnVibrato
    DW _tbe_cmdFnSetEnvelope
    DW _tbe_cmdFnSetTimbre
    DW _tbe_cmdFnSetPanning
    DW _tbe_cmdFnInstrumentSet
    DW _tbe_cmdFnInstrumentOff
    DW _tbe_cmdFnDelayedCut
    DW _tbe_cmdFnDelayedNote

; Note frequency table
; Octave range for CH1/CH2 is 2-8, CH3 is one lower (unless the waveform has 2 periods)
; Note indices start at C-2 and end at B-8

tbe_dNoteTable:
;        C     C#    D     D#    E     F     F#    G     G#    A     A#    B
    DW $02C, $09D, $107, $16B, $1CA, $223, $277, $2C7, $312, $358, $39B, $3DA ; Octave 2
    DW $416, $44E, $483, $4B5, $4E5, $511, $53C, $563, $589, $5AC, $5CE, $5ED ; Octave 3
    DW $60B, $627, $642, $65B, $672, $689, $69E, $6B2, $6C4, $6D6, $6E7, $6F7 ; Octave 4
    DW $706, $714, $721, $72D, $739, $744, $74F, $759, $762, $76B, $773, $77B ; Octave 5
    DW $783, $78A, $790, $797, $79D, $7A2, $7A7, $7AC, $7B1, $7B6, $7BA, $7BE ; Octave 6
    DW $7C1, $7C5, $7C8, $7CB, $7CE, $7D1, $7D4, $7D6, $7D9, $7DB, $7DD, $7DF ; Octave 7
    DW $7E1, $7E2, $7E4, $7E6, $7E7, $7E9, $7EA, $7EB, $7EC, $7ED, $7EE, $7EF ; Octave 8

;
; Noise (NR43) table
; This table maps notes from C-2 to B-6 for the NR43 register. Each value in this table
; consists of a DRF and SCF pairing that results in a unique period sorted from largest to
; smallest. There are 60 unique sounds that can be generated by CH4 for each step-width
; (for 7-bit just OR with 0x08)
;

tbe_dNoiseTable:
    DB $D7, $D6, $D5, $D4, $C7, $C6, $C5, $C4, $B7, $B6, $B5, $B4 ; Octave 2
    DB $A7, $A6, $A5, $A4, $97, $96, $95, $94, $87, $86, $85, $84 ; Octave 3
    DB $77, $76, $75, $74, $67, $66, $65, $64, $57, $56, $55, $54 ; Octave 4
    DB $47, $46, $45, $44, $37, $36, $35, $34, $27, $26, $25, $24 ; Octave 5
    DB $17, $16, $15, $14, $07, $06, $05, $04, $03, $02, $01, $00 ; Octave 6

; note table: 84 * 2 = 168 bytes
; command table: 21 * 2 = 42 bytes
; 210/256 bytes used, leaving 46 bytes for 23 additional commands (only 11 more are possible)

POPS
