#
# This workflow just builds everything using the makefile. Nothing is tested.
#

name: build
on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      BGB_DIR: ${{ github.workspace }}\bgb
      BGB_VERSION: 1.5.9
      RGBDS_DIR: ${{ github.workspace }}\rgbds
      RGBDS_VERSION: 0.5.2


    steps:
    - uses: actions/checkout@v2

    - name: Get GNU Make
      run: choco install make

    - name: Cache RGBDS
      id: cache-rgbds
      uses: actions/cache@v2
      with:
        path: ${{ env.RGBDS_DIR }}
        key: rgbds-${{ runner.os }}-${{ env.RGBDS_VERSION }}

    - name: Get RGBDS
      if: steps.cache-rgbds.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -OutFile rgbds.zip "https://github.com/gbdev/rgbds/releases/download/v${{env.RGBDS_VERSION}}/rgbds-${{env.RGBDS_VERSION}}-win64.zip"
        Expand-Archive -Path rgbds.zip -DestinationPath "${{ env.RGBDS_DIR }}"

    - name: Cache BGB
      id: cache-bgb
      uses: actions/cache@v2
      with:
        path: ${{ env.BGB_DIR }}
        key: bgb-${{ env.BGB_VERSION }}
    
    - name: Get BGB
      if: steps.cache-bgb.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -OutFile bgb.zip "https://bgb.bircd.org/bgb.zip"
        Expand-Archive -Path bgb.zip -DestinationPath "${{ env.BGB_DIR }}"

    - name: Build
      shell: bash
      run: |
        make BGB="bgb/bgb.exe" RGBDS="rgbds/" test
